name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # or any branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify the Node.js version you want

      - name: Install dependencies
        run: |
          cd test  # Change to your working directory
          yarn install

      - name: Build the project
        run: |
          cd test  # Change to your working directory
          yarn build

      - name: SSH to server and deploy
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}  # Store your server IP in GitHub Secrets
          SERVER_HOSTNAME: ${{ secrets.SERVER_HOSTNAME }}  # Store your server hostname in GitHub Secrets
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_ID }}  # Store your SSH private key in GitHub Secrets
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key root@$SERVER_IP 'bash -s' < ./deploy.sh  # Adjust the path to your deploy script
