name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js (if needed)
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # or any other version

      - name: Run shell script
        env:
          SERVER_IP: 206.189.139.190     # Pass the server IP as an environment variable
          SERVER_HOST: root  # Pass the server hostname as an environment variable
        run: |
          echo "Starting deployment process..."
          chmod +x ./deploy.sh
          ./deploy.sh
