name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - DEV  # Added DEV branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Deploy to Digital Ocean
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
        run: |
          echo "Starting deployment process..."
          chmod +x ./deploy.sh
          ./deploy.sh
