name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY_ID }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      - name: Test SSH connection to GitHub
        run: |
          ssh -T git@github.com || true

      - name: Clone the repository
        run: git clone git@github.com:sumit-linearloop/digitalocean-api.git /var/www/DEV

      - name: Run deploy script
        env:
          SERVER_IP: 206.189.139.190
          SERVER_HOST: root
        run: |
          echo "Starting deployment process..."
          chmod +x ./deploy.sh
          ./deploy.sh
